#!/usr/bin/env node
/**
 * Embeds resize-iframe-child.js into child-source.js so `withResizeChild` can
 * inline it without a filesystem read or a network fetch. Run before test and
 * publish; the generated file is committed so installs need no build step.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const child = readFileSync(join(root, "resize-iframe-child.js"), "utf8");
const out = `// Generated by scripts/embed-child.mjs — do not edit.
export const childScriptSource = ${JSON.stringify(child)};
`;
writeFileSync(join(root, "child-source.js"), out);
console.log("wrote child-source.js (%d bytes of child)", child.length);
